# Generated by Django 6.0.6 on 2026-07-23 09:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoredSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listOfBodies', models.JSONField(blank=True, default=list)),
                ('simulationSize', models.FloatField(default=0)),
                ('simulationTime', models.IntegerField(default=0)),
                ('bodyPoints', models.JSONField(blank=True, default=list)),
                ('ticksPerStorageUpdate', models.IntegerField(default=0)),
                ('ticksPerPageUpdate', models.IntegerField(default=0)),
                ('secondsPerSimulationTick', models.IntegerField(default=0)),
                ('name', models.TextField(default='')),
                ('image', models.ImageField(default='', upload_to='')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='PlanetaryOrbitSimulator.user')),
            ],
        ),
    ]
